# Generated by Django 5.2.1 on 2025-08-13 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор Телеграм')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Юзернейм')),
                ('first_name', models.CharField(blank=True, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, null=True, verbose_name='Фамилия')),
                ('role', models.CharField(blank=True, choices=[('A', 'Администратор'), ('B', 'Ст. Менеджер'), ('V', 'Менеджер'), ('G', 'Водитель'), ('D', 'Рабочий цеха'), ('E', 'Маляр'), ('F', 'Менеджер в цеху')], max_length=1, null=True, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(blank=True, choices=[('measurement', 'Замер'), ('delivery', 'Самостоятельный замер')], max_length=20, null=True, verbose_name='Тип заказа')),
                ('subtype', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Подтип заказа')),
                ('type_1_count', models.IntegerField(default=0, verbose_name='ПВХ, количество')),
                ('type_2_count', models.IntegerField(default=0, verbose_name='Фасад, количество')),
                ('type_3_count', models.IntegerField(default=0, verbose_name='Деревянные, количество')),
                ('type_4_count', models.IntegerField(default=0, verbose_name='Раздвижные, количество')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('measurement_added', 'Замер внесён'), ('take_size', 'Замер принят'), ('sent_to_size', 'Отправлен на замер'), ('sent_to_workshop', 'Отправлен в цех'), ('workshop_completed', 'Завершён цехом'), ('on_delivery', 'На доставке'), ('completed', 'Завершён'), ('canceled', 'Отменён')], default='created', max_length=30, verbose_name='Статус заказа')),
                ('chat_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Чат, в котором находится заказ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('work_place_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки в цех')),
                ('work_place_at_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения в цеху')),
                ('size_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала замера')),
                ('size_at_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения замера')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения')),
                ('measurement_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость замера')),
                ('genral_cost_info', models.CharField(blank=True, null=True, verbose_name='Статус оплаты')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Коментарии')),
                ('sizes', models.TextField(blank=True, null=True, verbose_name='Замеры')),
                ('choise_pay', models.CharField(blank=True, null=True, verbose_name='Способ оплаты')),
                ('payment_status', models.CharField(blank=True, choices=[('full_payment', 'Полная оплата'), ('advance', 'Аванс'), ('awaiting_payment', 'Ожидает доплаты')], editable=False, max_length=20, null=True, verbose_name='Статус оплаты')),
                ('current_work_place', models.CharField(blank=True, choices=[('first', 'Стол 1'), ('second', 'Стол 2'), ('thirt', 'Стол 3')], max_length=20, null=True, verbose_name='Стол в цехе')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('current_caption', models.TextField(blank=True, null=True, verbose_name='Текущее сообщение заказа')),
                ('active_messages_info', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='panel.client', verbose_name='Клиент')),
                ('cancellation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cans_orders', to='panel.user', verbose_name='Отменивший сотрудник')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='panel.user', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('type_1', 'Решетка на замках'), ('type_2', 'Решетка на шпингалете'), ('type_3', 'Вольер'), ('type_4', 'Ограничитель'), ('type_5', 'Дверь'), ('type_6', 'Нестандарт(На барашках)')], max_length=30, verbose_name='Тип изделия')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет')),
                ('price', models.IntegerField(default=0, verbose_name='Цена за единицу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='panel.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='panel.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Время назначения')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='panel.order')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='panel.user')),
            ],
            options={
                'verbose_name': 'Запись о назначении заказа',
                'verbose_name_plural': 'Журнал назначений заказов',
            },
        ),
    ]
