# Generated by Django 5.2.1 on 2025-07-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('A', 'Администратор'), ('B', 'Ст. Менеджер'), ('V', 'Менеджер'), ('G', 'Водитель'), ('D', 'Рабочий цеха'), ('E', 'Маляр')], max_length=1, null=True, verbose_name='Роль'),
        ),
    ]
