# Generated by Django 5.2.1 on 2025-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='window_type',
            field=models.CharField(blank=True, choices=[('type_1', 'Решетка на замках'), ('type_2', 'Решетка на шпингалете'), ('type_3', 'Вольер'), ('type_4', 'Ограничитель'), ('type_5', 'Дверь'), ('type_6', 'Нестандарт(На барашках)')], max_length=30, null=True, verbose_name='Тип окна (для замера)'),
        ),
    ]
