# Generated by Django 5.2.1 on 2025-07-12 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_user_options_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона (ID клиента)')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_type', models.CharField(blank=True, choices=[('measurement', 'Замер'), ('delivery', 'Доставка'), ('work_order', 'Заказ-наряд')], max_length=20, null=True, verbose_name='Тип заказа')),
                ('subtype', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подтип заказа')),
                ('window_type', models.CharField(blank=True, choices=[('pvc', 'ПВХ'), ('facade', 'Фасадное'), ('non_standard', 'Нестандарт')], max_length=20, null=True, verbose_name='Тип окна (для замера)')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('measurement_added', 'Замер внесён'), ('sent_to_workshop', 'Отправлен в цех'), ('workshop_completed', 'Завершён цехом'), ('painted', 'Покрашен'), ('on_delivery', 'На доставке'), ('completed', 'Завершён'), ('canceled', 'Отменён')], default='created', max_length=30, verbose_name='Статус заказа')),
                ('chat_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Чат, в котором находится заказ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('measurement_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость замера')),
                ('product_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость изделия')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость доставки')),
                ('payment_status', models.CharField(blank=True, choices=[('full_payment', 'Полная оплата'), ('advance', 'Аванс'), ('awaiting_payment', 'Ожидает доплаты')], max_length=20, null=True, verbose_name='Статус оплаты')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отмены')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='panel.client', verbose_name='Клиент')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='panel.user', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
