# Generated by Django 5.2.1 on 2025-07-12 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_client_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('measurement', 'Замер'), ('delivery', 'Доставка'), ('workOrder', 'Заказ-наряд')], max_length=20, null=True, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('A', 'Администратор'), ('B', 'Ст. Менеджер'), ('V', 'Менеджер'), ('G', 'Водитель'), ('D', 'Рабочий цеха'), ('E', 'Маляр'), ('F', 'Замерщик')], max_length=1, null=True, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='StartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture', models.TextField(blank=True, null=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, null=True)),
                ('call_data', models.CharField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.order')),
            ],
        ),
    ]
