# Generated by Django 5.2.1 on 2025-07-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_order_window_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cans_orders', to='panel.user', verbose_name='Отменивший сотрудник сотрудник'),
        ),
    ]
