# Generated by Django 5.2.1 on 2025-07-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_order_cancellation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_caption',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
