# Generated by Django 5.2.1 on 2025-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_order_current_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_work_place',
            field=models.CharField(blank=True, choices=[('first', 'Стол 1'), ('second', 'Стол 2'), ('thirt', 'Стол 3')], max_length=20, null=True),
        ),
    ]
