# Generated by Django 5.2.1 on 2025-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_order_current_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость монтажа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('measurement_added', 'Замер внесён'), ('sent_to_workshop', 'Отправлен в цех'), ('workshop_completed', 'Завершён цехом'), ('on_delivery', 'На доставке'), ('completed', 'Завершён'), ('canceled', 'Отменён')], default='created', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
