# Generated by Django 5.2.1 on 2025-07-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_client_options_alter_order_cancellation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='canceled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время отмены'),
        ),
    ]
