# Generated by Django 5.2.1 on 2025-07-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_alter_order_canceled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='window_type',
        ),
        migrations.AddField(
            model_name='order',
            name='type_1_count',
            field=models.IntegerField(default=0, verbose_name='Решетка на замках, количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_2_count',
            field=models.IntegerField(default=0, verbose_name='Решетка на шпингалете, количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_3_count',
            field=models.IntegerField(default=0, verbose_name='Вольер, количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_4_count',
            field=models.IntegerField(default=0, verbose_name='Ограничитель, количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_5_count',
            field=models.IntegerField(default=0, verbose_name='Дверь, количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_6_count',
            field=models.IntegerField(default=0, verbose_name='Нестандарт(На барашках)'),
        ),
    ]
