# Generated by Django 5.2.1 on 2025-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_remove_order_window_type_order_type_1_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active_messages_info',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
