# Generated by Django 5.2.1 on 2025-07-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_order_active_messages_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарии'),
        ),
        migrations.AddField(
            model_name='order',
            name='genral_cost_info',
            field=models.TextField(blank=True, null=True, verbose_name='Расчет'),
        ),
    ]
