# Generated by Django 5.2.1 on 2025-07-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_remove_order_delivery_cost_remove_order_product_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sizes',
            field=models.TextField(blank=True, null=True, verbose_name='Замеры'),
        ),
    ]
