# Generated by Django 5.2.1 on 2025-07-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_order_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='choise_pay',
            field=models.CharField(blank=True, null=True, verbose_name='Способ оплаты'),
        ),
    ]
