# Generated by Django 5.2.1 on 2025-08-09 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_order_choise_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type_5_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_6_count',
        ),
        migrations.AlterField(
            model_name='order',
            name='type_1_count',
            field=models.IntegerField(default=0, verbose_name='ПВХ, количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_2_count',
            field=models.IntegerField(default=0, verbose_name='Фасад, количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_3_count',
            field=models.IntegerField(default=0, verbose_name='Деревянные, количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_4_count',
            field=models.IntegerField(default=0, verbose_name='Раздвижные, количество'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('type_1', 'Решетка на замках'), ('type_2', 'Решетка на шпингалете'), ('type_3', 'Вольер'), ('type_4', 'Ограничитель'), ('type_5', 'Дверь'), ('type_6', 'Нестандарт(На барашках)')], max_length=30, verbose_name='Тип изделия')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет')),
                ('price', models.IntegerField(default=0, verbose_name='Цена за единицу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='panel.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
