# Generated by Django 5.2.1 on 2025-08-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_remove_order_type_5_count_remove_order_type_6_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='genral_cost_info',
            field=models.CharField(blank=True, null=True, verbose_name='Статус оплаты'),
        ),
    ]
