# Generated by Django 5.2.1 on 2025-08-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_alter_order_genral_cost_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sizes',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Замеры'),
        ),
    ]
