# Generated by Django 5.2.1 on 2025-08-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_order_completed_at_alter_order_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='canceled_at',
        ),
    ]
