# Generated by Django 5.2.1 on 2025-08-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_remove_order_canceled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Время назначения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='panel.user')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='panel.order')),
            ],
            options={
                'verbose_name': 'Запись о назначении заказа',
                'verbose_name_plural': 'Журнал назначений заказов',
            },
        ),
    ]
