# Generated by Django 5.2.1 on 2025-08-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_orderassignmentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала замера'),
        ),
        migrations.AddField(
            model_name='order',
            name='size_at_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения замера'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_place_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки в цех'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_place_at_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения в цеху'),
        ),
    ]
